### ISSUE TITLE
Support for HoMM3 on Steam

### ISSUE THREAD

**Issue by Peneheals** [Peneheals/ihhh#56]

**Comment by meneken17** [comment]
Steam only has the HoMM HD edition (not HD Mod) which is not compatible with HotA.
You might want to add this to the readme.

**Comment by Peneheals** [comment]
> Steam only has the HoMM HD edition (not HD Mod) which is not compatible with HotA. You might want to add this to the readme.

Ah, [it looks like](https://store.steampowered.com/app/297000/Heroes_of_Might__Magic_III__HD_Edition/) you are absolutely right. Thanks for pointing this out!
